<?php

namespace deadmantfa\yii2\zoho\auth;

use yii\authclient\OAuth2;
use yii\authclient\OAuthToken;

class ZohoAuthClient extends OAuth2
{
    public $authUrl = 'https://accounts.zoho.com/oauth/v2/auth';

    public $tokenUrl = 'https://accounts.zoho.com/oauth/v2/token';

    public $apiBaseUrl = 'https://accounts.zoho.com/oauth/v2/';

    public $scope = 'ZohoInventory.FullAccess.all';

    public $returnUrl;

    public $accessType = 'offline';

    public $prompt = 'Consent';

    public function init()
    {
        parent::init();
        $this->setReturnUrl($this->returnUrl);
    }

    protected function defaultName()
    {
        return 'zoho';
    }

    protected function defaultTitle()
    {
        return 'Zoho Auth Client';
    }

    protected function defaultViewOptions()
    {
        return [
            'popupWidth' => 800,
            'popupHeight' => 500,
        ];
    }

    /**
     * @inheritDoc
     */
    protected function initUserAttributes()
    {
        $params = $this->getAccessToken()->params;
        return [

            'access_token' => $params['access_token'],
            'refresh_token' => $params['refresh_token'],
            'expires_in' => (string)$params['expires_in'],
        ];
    }

    public function buildAuthUrl(array $params = [])
    {
        $params['prompt'] = $this->prompt;
        $params['access_type'] = $this->accessType;
        return parent::buildAuthUrl($params); // TODO: Change the autogenerated stub
    }

}
